//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiccanRede.Properties {
    using System;
    
    
    /// <summary>
    ///   npc1 strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiccanRede.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastala kritická chyba, je nutné ukončit aplikaci..
        /// </summary>
        internal static string Critical_Error {
            get {
                return ResourceManager.GetString("Critical_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ztratilo se zařízení direct 3D, pokouším se o obnovu..
        /// </summary>
        internal static string Graphic_Core_Device_Lost {
            get {
                return ResourceManager.GetString("Graphic_Core_Device_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ztratilo se zařízení direct 3D a není možné ho nyní obnovit..
        /// </summary>
        internal static string Graphic_Core_Device_Lost_Permanent {
            get {
                return ResourceManager.GetString("Graphic_Core_Device_Lost_Permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastala vnitřní chyba driveru grafické karty..
        /// </summary>
        internal static string Graphic_Core_Driver_Internal_Error {
            get {
                return ResourceManager.GetString("Graphic_Core_Driver_Internal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezdařila se inicializace vykreslovacího jádra..
        /// </summary>
        internal static string Graphic_Core_Init_Error {
            get {
                return ResourceManager.GetString("Graphic_Core_Init_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezdařilo se vytvoření instance třídy Input..
        /// </summary>
        internal static string Input_Core_Init_Error {
            get {
                return ResourceManager.GetString("Input_Core_Init_Error", resourceCulture);
            }
        }
    }
}
